# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '\u6295\u7968\u9009\u9879', 'verbose_name_plural': '\u6295\u7968\u9009\u9879'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u6295\u7968\u95ee\u9898', 'verbose_name_plural': '\u6295\u7968\u95ee\u9898'},
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(default='', upload_to='polls/img/', verbose_name='\u56fe\u7247\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='\u9009\u9879\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='\u95ee\u9898\u5185\u5bb9'),
        ),
    ]
