# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170214_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc_text',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='\u8c03\u67e5\u63cf\u8ff0'),
        ),
    ]
