# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170214_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[('0', '\u5df2\u505c\u7528'), ('1', '\u6b63\u5e38')], default=1),
        ),
    ]
